import { createHash } from "node:crypto";
import type { AnalysisDocument, AnalysisResult } from "./analyzer.js";

export const ANALYSIS_SCHEMA_VERSION="professional-extraction-v1";
export interface AnalysisCacheEntry { key:string; documentFingerprint:string; model:string; promptVersion:string; schemaVersion:string; createdAt:string; result:AnalysisResult }
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
export const documentFingerprint=(document:Pick<AnalysisDocument,"sections">)=>digest(document.sections.map(({text})=>text).join("\n\u000c\n"));
export const analysisCacheKey=(fingerprint:string,model:string,promptVersion:string,schemaVersion=ANALYSIS_SCHEMA_VERSION)=>digest([fingerprint,model,promptVersion,schemaVersion].join("|"));
export function findCachedAnalysis(entries:readonly AnalysisCacheEntry[],document:AnalysisDocument,model:string,promptVersion:string,schemaVersion=ANALYSIS_SCHEMA_VERSION){const fingerprint=documentFingerprint(document),key=analysisCacheKey(fingerprint,model,promptVersion,schemaVersion);return {fingerprint,key,entry:entries.find(item=>item.key===key)};}
export function textSimilarity(left:string,right:string):number{const words=(value:string)=>new Set(value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().match(/[a-z0-9]{3,}/g)??[]),a=words(left),b=words(right);if(!a.size&&!b.size)return 1;let common=0;for(const word of a)if(b.has(word))common++;return common/(a.size+b.size-common);}
export function bindCachedAnalysis(entry:AnalysisCacheEntry,document:AnalysisDocument):AnalysisResult{const result=structuredClone(entry.result),achievementIds=new Map<string,string>();for(const fact of result.facts)if(fact.category==="ACHIEVEMENT"&&!achievementIds.has(fact.entityId))achievementIds.set(fact.entityId,`achievement:provisional:${digest(`${document.id}|${fact.entityId}`).slice(0,24)}`);for(const fact of result.facts){const matchingSection=document.sections.find(section=>section.text.normalize("NFC").replace(/\s+/g," ").includes(fact.source.quote.normalize("NFC").replace(/\s+/g," "))),section=matchingSection?.label??fact.source.section;fact.source={...fact.source,documentId:document.id,name:document.name,section,location:section};fact.sources=fact.sources.map(source=>({...source,documentId:document.id,name:document.name,section,location:section}));const mapped=achievementIds.get(fact.entityId);if(mapped){fact.entityId=mapped;fact.key=`${mapped}:${fact.field}`;}}return result;}
