import { createHash } from "node:crypto";
import type { CandidateFact } from "./truth.js";

const hash=(value:string)=>createHash("sha256").update(value).digest("hex").slice(0,24);
export const normalizeSemantic=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(groupe|group)\b/g," ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const companyAliases=new Map([["adient","johnson controls"],["simea l acoustics","simea l acoustics"]]);
const normalizeCompany=(value:string)=>companyAliases.get(normalizeSemantic(value))??normalizeSemantic(value).replace(/\b(sa|sas|sarl|gmbh|ag)\b/g,"").trim();
export function canonicalizeProfessionalEntities(input:readonly CandidateFact[]):CandidateFact[]{const facts:CandidateFact[]=input.map(item=>structuredClone(item)),experiences=new Map<string,{company?:string;start?:string;end?:string}>();for(const fact of facts.filter(item=>item.category==="EXPERIENCE")){const values=experiences.get(fact.entityId)??{};if(fact.field==="company")values.company=fact.structuredValue??fact.canonical;if(fact.field==="startDate")values.start=fact.structuredValue??fact.canonical;if(fact.field==="endDate")values.end=fact.structuredValue??fact.canonical;experiences.set(fact.entityId,values);}const remap=new Map<string,string>();for(const [id,value] of experiences){if(!value.company||(!value.start&&!value.end)||id.includes(":unresolved:"))continue;const signature=[normalizeCompany(value.company),normalizeSemantic(value.start??""),normalizeSemantic(value.end??"")].join("|");remap.set(id,`experience:${hash(signature)}`);}for(const fact of facts){const mapped=remap.get(fact.entityId);if(mapped){fact.entityId=mapped;fact.key=`${mapped}:${fact.field}`;}if((fact.category==="ACHIEVEMENT"||fact.category==="SKILL")&&fact.field==="experienceId"&&fact.structuredValue){const linked=remap.get(fact.structuredValue);if(linked){fact.structuredValue=linked;fact.canonical=linked;}}}
 const achievements=new Map<string,CandidateFact[]>();for(const fact of facts.filter(item=>item.category==="ACHIEVEMENT"&&item.field!=="experienceId"&&!item.entityId.startsWith("achievement:semantic:"))){const list=achievements.get(fact.entityId)??[];list.push(fact);achievements.set(fact.entityId,list);}const achievementRemap=new Map<string,string>(),anchors=new Map<string,string>();for(const [id,items] of achievements){const values=items.filter(item=>["context","action","result","metric"].includes(item.field)).map(item=>normalizeSemantic(item.structuredValue??item.canonical)).filter(Boolean),anchor=[...new Set(values)].sort().join("|");if(!anchor)continue;const existing=anchors.get(anchor),canonical=existing??`achievement:semantic:${hash(anchor)}`;anchors.set(anchor,canonical);achievementRemap.set(id,canonical);}for(const fact of facts){const mapped=achievementRemap.get(fact.entityId);if(mapped){fact.entityId=mapped;fact.key=`${mapped}:${fact.field}`;}}
 for(const fact of facts.filter(item=>item.origin==="AUTOMATIC")){fact.id=`fact:${hash(`${fact.category}|${fact.entityId}|${fact.field}|${normalizeSemantic(fact.structuredValue??fact.canonical)}`)}`;}return facts;}
