import assert from "node:assert/strict";
import test from "node:test";
import { canonicalizeProfessionalEntities } from "./consolidation.js";
import { consolidateFacts, type CandidateFact } from "./truth.js";
const make=(id:string,category:"EXPERIENCE"|"ACHIEVEMENT",entityId:string,field:string,value:string,documentId:string):CandidateFact=>({id,type:`${category}.${field}`,category,entityId,field,key:`${entityId}:${field}`,canonical:value,structuredValue:value,source:{documentId,name:`${documentId}.docx`,location:"Section 1",section:"Section 1",quote:value},sources:[{documentId,name:`${documentId}.docx`,location:"Section 1",section:"Section 1",quote:value}],confidence:.9,status:"PROPOSED",allowedAlternatives:[],tags:[],active:true,origin:"AUTOMATIC",extraction:{method:"OPENAI",model:"fake",promptVersion:"v2",analyzedAt:"2026-01-01"},history:[]});
test("consolide les variantes fortes d’une expérience et conserve les sources",()=>{const facts=[make("a1","EXPERIENCE","old-a","company","SIMEA (Groupe L-Acoustics)","a"),make("a2","EXPERIENCE","old-a","startDate","2021","a"),make("a3","EXPERIENCE","old-a","endDate","2024","a"),make("b1","EXPERIENCE","old-b","company","SIMEA - Groupe L-Acoustics","b"),make("b2","EXPERIENCE","old-b","startDate","2021","b"),make("b3","EXPERIENCE","old-b","endDate","2024","b")],canonical=canonicalizeProfessionalEntities(facts);assert.equal(new Set(canonical.map(f=>f.entityId)).size,1);const consolidated=consolidateFacts(canonical);assert.ok(consolidated.some(f=>f.field==="startDate"&&f.sources.length===2));});
test("ne fusionne pas deux expériences sans signature forte",()=>{const facts=[make("a","EXPERIENCE","unresolved-a","company","Atelier Alpha","a"),make("b","EXPERIENCE","unresolved-b","company","Atelier Alpha","b")],canonical=canonicalizeProfessionalEntities(facts);assert.equal(new Set(canonical.map(f=>f.entityId)).size,2);});
test("un même localRef documentaire ne mélange jamais pompe et anti-TMS",()=>{const facts=[make("p1","ACHIEVEMENT","achievement:provisional:pump","action","Avant-projet ligne pompe 600 k€ et 40 k€","doc-pompe"),make("t1","ACHIEVEMENT","achievement:provisional:tms","action","Conception d’un dispositif anti-TMS","doc-tms")],canonical=canonicalizeProfessionalEntities(facts);assert.equal(new Set(canonical.map(f=>f.entityId)).size,2);assert.equal(consolidateFacts(canonical).length,2);});
test("fusionne uniquement deux réalisations aux ancres normalisées identiques",()=>{const facts=[make("a","ACHIEVEMENT","achievement:provisional:a","action","Réduction des rebuts de 15 %","a"),make("b","ACHIEVEMENT","achievement:provisional:b","action","Réduction des rebuts de 15 %","b")],consolidated=consolidateFacts(canonicalizeProfessionalEntities(facts));assert.equal(consolidated.length,1);assert.equal(consolidated[0]?.sources.length,2);});
