import assert from "node:assert/strict";
import test from "node:test";
import { consolidateFacts, decideFact, findContradictions } from "./truth.js";
import { proposeFacts } from "./proposals.js";
const extract=(id:string,text:string)=>proposeFacts(id,`Dossier de compétences ${id}.docx`,[{label:"Section 1",text}]);
test("extrait expériences et projet atomiques sans titres",()=>{const facts=extract("a","PROFIL\nEXPÉRIENCE INDUSTRIELLE\nExpérience: LAPP | Responsable Lean | Genève | 2020-01 | 2025-04\nProjet: Réduction des rebuts | Action: Standardiser le réglage | Résultat: -25 % de rebuts");assert.ok(facts.some(f=>f.field==="company"&&f.structuredValue==="LAPP"));assert.ok(facts.some(f=>f.field==="metric"&&f.structuredValue==="-25 %"));assert.ok(!facts.some(f=>f.canonical==="PROFIL"||f.canonical==="EXPÉRIENCE INDUSTRIELLE"));});
test("consolide doublons et limite les contradictions à une entité et un champ",()=>{const lapp=extract("a","Fin LAPP : avril 2025"),duplicate=extract("b","Fin LAPP : avril 2025"),conflict=extract("c","Fin LAPP : mai 2025"),other=extract("d","Expérience: ActBlue | Ingénieur Méthodes | Lyon | 2018 | 2020");const consolidated=consolidateFacts([...lapp,...duplicate,...other]);assert.equal(consolidated.find(f=>f.entityId==="experience:lapp")?.sources.length,2);assert.equal(findContradictions(consolidated).length,0);const contradictions=findContradictions([...consolidated,...conflict]);assert.equal(contradictions.length,1);assert.equal(contradictions[0]?.field,"endDate");});
test("classe une expérience ambiguë et ne valide jamais automatiquement",()=>{const facts=extract("a","Expérience: Entreprise Fictive");assert.ok(facts.length);assert.ok(facts.every(f=>f.status==="NEEDS_CONFIRMATION"));assert.ok(facts.every(f=>f.status!=="VERIFIED"));});
test("une réanalyse peut préserver un fait vérifié",()=>{const verified=decideFact(extract("a","Fin LAPP : avril 2025")[0]!,"verify");const generated=extract("b","Fin LAPP : mai 2025");assert.equal(consolidateFacts([verified,...generated]).find(f=>f.id===verified.id)?.status,"VERIFIED");});
