import { createHash } from "node:crypto";
import { consolidateFacts, type CandidateFact, type FactCategory, type FactStatus, type SourceRef } from "./truth.js";

type SectionKind="EXPERIENCE"|"SKILL"|"ACHIEVEMENT"|"EDUCATION"|"LANGUAGE"|"PROFILE"|"OTHER";
const sectionPatterns:Array<[SectionKind,RegExp]>=[
 ["EXPERIENCE",/^(exp[ée]riences?(?: professionnelles?| industrielles?)?|parcours(?: professionnel)?)$/i],
 ["SKILL",/^(comp[ée]tences?|expertise|m[ée]thodes?|outils?|logiciels?|technologies?)$/i],
 ["ACHIEVEMENT",/^(r[ée]alisations?|projets?|r[ée]sultats?)$/i],
 ["EDUCATION",/^(formations?|dipl[oô]mes?|certifications?)$/i],
 ["LANGUAGE",/^langues?$/i], ["PROFILE",/^(profil|coordonn[ée]es?|mobilit[ée])$/i]
];
const roleWords=/responsable|manager|ing[ée]nieur|technicien|directeur|chef|consultant|coordinateur|sp[ée]cialiste|lean|quality|production|m[ée]thodes/i;
const dateToken=String.raw`(?:\d{1,2}[/.]\d{4}|\d{4}|(?:janvier|f[ée]vrier|mars|avril|mai|juin|juillet|ao[uû]t|septembre|octobre|novembre|d[ée]cembre)\s+\d{4})`;
const dateRange=new RegExp(`(?:depuis\\s+)?(${dateToken})\\s*(?:-|–|—|à|au)\\s*(${dateToken}|aujourd['’]hui|pr[ée]sent)|depuis\\s+(${dateToken})`,"i");
const metricPattern=/(?:[-+]?\d+(?:[.,]\d+)?\s*(?:%|€|CHF|k€|M€|collaborateurs?|personnes?|jours?|heures?|semaines?|mois|pi[èe]ces?|unit[ée]s?|projets?|sites?))/gi;
const knownSkills=/\b(5S|SMED|Kaizen|Lean|Six Sigma|DMAIC|AMDEC|FMEA|SAP|Excel|Power BI|AutoCAD|SolidWorks|Kanban|TPM|VSM)\b/gi;
const slug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("fr").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const entity=(prefix:string,value:string)=>`${prefix}:${slug(value)||createHash("sha1").update(value).digest("hex").slice(0,10)}`;
export function normalizeDocumentText(text:string):string[]{return text.normalize("NFC").replace(/[\u00a0\u202f]/g," ").replace(/[‐‑‒–—]/g,"–").replace(/^[ \t]*[•▪◦●·][ \t]*/gm,"• ").replace(/[ \t]+/g," ").split(/\r?\n/).map(line=>line.trim()).filter(Boolean);}
function fact(category:FactCategory,entityId:string,field:string,value:string,source:SourceRef,confidence=.8,status:FactStatus="PROPOSED"):CandidateFact{const id=`fact:${createHash("sha256").update(`${category}|${entityId}|${field}|${value.toLocaleLowerCase("fr")}`).digest("hex").slice(0,24)}`;return {id,type:`${category}.${field}`.toUpperCase(),category,entityId,field,key:`${entityId}:${field}`,canonical:value,structuredValue:value,source,sources:[source],confidence,status,allowedAlternatives:[],tags:[],active:true,origin:"AUTOMATIC",history:[{at:new Date().toISOString(),action:"CREATED",actor:"extractor"}]};}
const sectionOf=(line:string)=>sectionPatterns.find(([,pattern])=>pattern.test(line.replace(/[:：]$/,"")))?.[0];
const looksCompany=(line:string)=>!sectionOf(line)&&line.length>=2&&line.length<80&&!roleWords.test(line)&&(/^[A-ZÀ-ÖØ-Ý0-9&.' -]+$/.test(line)||/\b(SA|SAS|SARL|GmbH|AG|Group|Industries?)\b/i.test(line));
function addSkills(output:CandidateFact[],text:string,source:SourceRef){const values=[...text.matchAll(knownSkills)].map(match=>match[1]!);for(const value of [...new Set(values)])output.push(fact("SKILL",entity("skill",value),"competency",value,source,.88));}
function addAchievement(output:CandidateFact[],text:string,experienceId:string|undefined,source:SourceRef){const clean=text.replace(/^•\s*/,"").trim();if(!clean)return;const id=entity("achievement",`${experienceId??"unassigned"}-${clean}`);const status:FactStatus=experienceId?"PROPOSED":"NEEDS_CONFIRMATION";output.push(fact("ACHIEVEMENT",id,"action",clean,source,experienceId ? .82 : .58,status));if(experienceId)output.push(fact("ACHIEVEMENT",id,"experienceId",experienceId,source,.9));const metrics=[...clean.matchAll(metricPattern)].map(match=>match[0].trim());if(metrics.length){output.push(fact("ACHIEVEMENT",id,"result",clean,source,.84,status));for(const value of metrics)output.push(fact("ACHIEVEMENT",id,"metric",value,source,.9,status));}addSkills(output,clean,source);}
export function proposeFacts(documentId:string,name:string,sections:readonly {label:string;text:string}[]):CandidateFact[]{const output:CandidateFact[]=[];let currentSection:SectionKind="OTHER",currentExperience:string|undefined;const entries=sections.flatMap(section=>normalizeDocumentText(section.text).map((line,index)=>({line,label:section.label,lineNumber:index+1})));for(let cursor=0;cursor<entries.length;cursor++){const entry=entries[cursor]!,line=entry.line,source={documentId,name,location:`${entry.label}, ligne ${entry.lineNumber}`};const heading=sectionOf(line);if(heading){currentSection=heading;if(heading!=="EXPERIENCE"&&heading!=="ACHIEVEMENT")currentExperience=undefined;continue;}
 const synthetic=line.match(/^(?:Exp[ée]rience)\s*:\s*([^|]+)(?:\|([^|]+))?(?:\|([^|]+))?(?:\|([^|]+))?(?:\|([^|]+))?/i);if(synthetic){const company=synthetic[1]!.trim(),role=synthetic[2]?.trim(),id=entity("experience",`${company}-${role??"ambiguous"}`),ambiguous=!role||!synthetic[4];for(const [field,value] of [["company",company],["role",role],["location",synthetic[3]?.trim()],["startDate",synthetic[4]?.trim()],["endDate",synthetic[5]?.trim()]] as const)if(value)output.push(fact("EXPERIENCE",id,field,value,source,ambiguous ? .58 : .9,ambiguous?"NEEDS_CONFIRMATION":"PROPOSED"));currentExperience=id;continue;}
 const dated=line.match(/^Fin\s+([^:]+)\s*:\s*(.+)$/i);if(dated){output.push(fact("EXPERIENCE",entity("experience",dated[1]!),"endDate",dated[2]!.trim(),source,.85));continue;}
 const project=line.match(/^(?:Projet|Réalisation)\s*:\s*([^|]+)(?:\|\s*Action\s*:\s*([^|]+))?(?:\|\s*Résultat\s*:\s*(.+))?/i);if(project){const id=entity("achievement",project[1]!);output.push(fact("ACHIEVEMENT",id,"context",project[1]!.trim(),source,.85));if(project[2])output.push(fact("ACHIEVEMENT",id,"action",project[2].trim(),source,.85));if(project[3])addAchievement(output,project[3],currentExperience,source);continue;}
 const range=line.match(dateRange);if(range){const previous=entries[cursor-1]?.line,before=entries[cursor-2]?.line;let company:string|undefined,role:string|undefined;if(previous&&before){if(roleWords.test(previous)&&looksCompany(before)){role=previous;company=before;}else if(looksCompany(previous)&&roleWords.test(before)){company=previous;role=before;}}const location=line.slice(0,range.index).trim().replace(/[|•,;\-–—]+$/g,"").trim()||undefined;const start=(range[1]??range[3])?.trim(),end=range[2]?.trim()??(range[3]?"présent":undefined);const reliable=Boolean(company&&role),id=entity("experience",`${company??"inconnue"}-${role??start??line}`),status:FactStatus=reliable?"PROPOSED":"NEEDS_CONFIRMATION",confidence=reliable ? .9 : .55;for(const [field,value] of [["company",company],["role",role],["location",location],["startDate",start],["endDate",end]] as const)if(value)output.push(fact("EXPERIENCE",id,field,value,source,confidence,status));currentExperience=id;currentSection="EXPERIENCE";continue;}
 if(line.startsWith("• ")){if(currentSection==="EXPERIENCE"||currentSection==="ACHIEVEMENT")addAchievement(output,line,currentExperience,source);else if(currentSection==="SKILL")addSkills(output,line,source);else if(currentSection==="EDUCATION")output.push(fact("EDUCATION",entity("education",line),"qualification",line.slice(2),source,.78));else if(currentSection==="LANGUAGE")output.push(fact("LANGUAGE",entity("language",line),"level",line.slice(2),source,.72));continue;}
 if(currentSection==="SKILL"){for(const value of line.split(/[,;•]/).map(item=>item.trim()).filter(Boolean))output.push(fact("SKILL",entity("skill",value),"competency",value,source,.76));continue;}if(currentSection==="EDUCATION"){output.push(fact("EDUCATION",entity("education",line),"qualification",line,source,.75));continue;}if(currentSection==="LANGUAGE"){output.push(fact("LANGUAGE",entity("language",line.split(/[-–—:]/)[0]??line),"level",line,source,.72));continue;}
 const labelled=line.match(/^(Comp[ée]tences?|Logiciels?|Technologies?|M[ée]thodes?|Langues?|Dipl[oô]mes?|Certifications?)\s*:\s*(.+)$/i);if(labelled){const kind=sectionOf(labelled[1]!)??"SKILL";for(const value of labelled[2]!.split(/[,;]/).map(item=>item.trim()).filter(Boolean)){const category:FactCategory=kind==="LANGUAGE"?"LANGUAGE":kind==="EDUCATION"?"EDUCATION":"SKILL";output.push(fact(category,entity(category.toLowerCase(),value),category==="LANGUAGE"?"level":category==="EDUCATION"?"qualification":"competency",value,source,.8));}continue;}
 const identity=line.match(/^(Nom|Email|T[ée]l[ée]phone|Adresse|Mobilit[ée]|Disponibilit[ée])\s*:\s*(.+)$/i);if(identity){const field=slug(identity[1]!),category:FactCategory=/mobilite|disponibilite/.test(field)?"PREFERENCES":"IDENTITY";output.push(fact(category,entity(category.toLowerCase(),field),field,identity[2]!.trim(),source,.8));}
 }return consolidateFacts(output);}
