import { createHash, randomUUID } from "node:crypto";
import { consolidateFacts, type CandidateFact, type FactCategory, type FactStatus, type SourceRef } from "./truth.js";
const headings=new Set(["PROFIL","EXPÉRIENCE","EXPERIENCE","EXPÉRIENCE INDUSTRIELLE","COMPÉTENCES","COMPETENCES","FORMATION","LANGUES","PROJETS","RÉALISATIONS"]);
const slug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("fr").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const entity=(prefix:string,value:string)=>`${prefix}:${slug(value)||createHash("sha1").update(value).digest("hex").slice(0,10)}`;
function fact(category:FactCategory,entityId:string,field:string,value:string,source:SourceRef,confidence=.8,status:FactStatus="PROPOSED"):CandidateFact{return {id:randomUUID(),type:`${category}.${field}`.toUpperCase(),category,entityId,field,key:`${entityId}:${field}`,canonical:value,structuredValue:value,source,sources:[source],confidence,status,allowedAlternatives:[],tags:[],active:true,origin:"AUTOMATIC",history:[{at:new Date().toISOString(),action:"CREATED",actor:"extractor"}]};}
export function proposeFacts(documentId:string,name:string,sections:readonly {label:string;text:string}[]):CandidateFact[]{const output:CandidateFact[]=[];for(const section of sections){for(const raw of section.text.split(/\r?\n|(?<=\.)\s{2,}/)){const line=raw.trim();if(line.length<3||headings.has(line.toLocaleUpperCase("fr"))||/^[A-ZÀ-ÖØ-Ý\s]{3,40}$/.test(line))continue;const source={documentId,name,location:section.label};
 const experience=line.match(/^(?:Expérience|Experience)\s*:\s*([^|]+)(?:\|([^|]+))?(?:\|([^|]+))?(?:\|([^|]+))?(?:\|([^|]+))?/i);if(experience){const company=experience[1]!.trim(),role=experience[2]?.trim(),id=entity("experience",role?`${company}-${role}`:company);const values:[[string,string|undefined],...Array<[string,string|undefined]>]=[["company",company],["role",role],["location",experience[3]?.trim()],["startDate",experience[4]?.trim()],["endDate",experience[5]?.trim()]];const ambiguous=!role||!experience[4];for(const [field,value] of values)if(value)output.push(fact("EXPERIENCE",id,field,value,source,ambiguous ? .55 : .9,ambiguous?"NEEDS_CONFIRMATION":"PROPOSED"));continue;}
 const dated=line.match(/^Fin\s+([^:]+)\s*:\s*(.+)$/i);if(dated){output.push(fact("EXPERIENCE",entity("experience",dated[1]!),"endDate",dated[2]!.trim(),source,.85));continue;}
 const project=line.match(/^(?:Projet|Réalisation)\s*:\s*([^|]+)(?:\|\s*Action\s*:\s*([^|]+))?(?:\|\s*Résultat\s*:\s*(.+))?/i);if(project){const id=entity("achievement",project[1]!);output.push(fact("ACHIEVEMENT",id,"context",project[1]!.trim(),source,.85));if(project[2])output.push(fact("ACHIEVEMENT",id,"action",project[2].trim(),source,.85));if(project[3]){output.push(fact("ACHIEVEMENT",id,"result",project[3].trim(),source,.85));const number=project[3].match(/[-+]?\d+(?:[.,]\d+)?\s*%?/);if(number)output.push(fact("ACHIEVEMENT",id,"metric",number[0],source,.9));}continue;}
 const labelled=line.match(/^(Compétences?|Logiciels?|Technologies?|Méthodes?|Langues?|Diplômes?|Certifications?)\s*:\s*(.+)$/i);if(labelled){const label=slug(labelled[1]!),category:FactCategory=label.startsWith("langue")?"LANGUAGE":label.startsWith("diplome")||label.startsWith("certification")?"EDUCATION":"SKILL";for(const value of labelled[2]!.split(/[,;]/).map(item=>item.trim()).filter(Boolean))output.push(fact(category,entity(category.toLowerCase(),value),label,value,source,.85));continue;}
 const identity=line.match(/^(Nom|Email|Téléphone|Adresse|Mobilité|Disponibilité)\s*:\s*(.+)$/i);if(identity){const field=slug(identity[1]!),category:FactCategory=/mobilite|disponibilite/.test(field)?"PREFERENCES":"IDENTITY";output.push(fact(category,entity(category.toLowerCase(),field),field,identity[2]!.trim(),source,.8));}
 }}return consolidateFacts(output);}
