import { createHash } from "node:crypto";
import { consolidateFacts, type CandidateFact, type FactCategory, type FactStatus, type SourceRef } from "./truth.js";

type SectionKind="EXPERIENCE"|"SKILL"|"ACHIEVEMENT"|"EDUCATION"|"LANGUAGE"|"PROFILE"|"OTHER";
interface TextLine { text:string; section:string; line:number; heading?:SectionKind }
export interface ParsedBlock { documentId:string; section:string; startLine:number; endLine:number; kind:SectionKind; lines:string[]; company?:string; role?:string; location?:string; startDate?:string; endDate?:string; value?:string; confidence:number; resolved:boolean; anchor:string }
const sectionPatterns:Array<[SectionKind,RegExp]>=[["EXPERIENCE",/^(?:(?:autres?\s+)?exp[ée]riences?(?: professionnelles?| industrielles?)?(?:\s*[–—-]\s*suite)?|parcours(?: professionnel)?)$/i],["SKILL",/^(comp[ée]tences?|expertise|m[ée]thodes?|outils?|logiciels?|technologies?)$/i],["ACHIEVEMENT",/^(r[ée]alisations?|projets?|r[ée]sultats?)$/i],["EDUCATION",/^(formations?|dipl[oô]mes?|certifications?|cursus universitaire)$/i],["LANGUAGE",/^langues?$/i],["PROFILE",/^(profil|coordonn[ée]es?|mobilit[ée])$/i]];
const roleWords=/\b(responsable|manager|ing[ée]nieur|technicien|directeur|chef|consultant|coordinateur|sp[ée]cialiste|formateur|stagiaire|lean|quality|production|m[ée]thodes|industrialisation|am[ée]lioration continue)\b/i;
const actionWords=/^(aligner|animer|accompagner|concevoir|mettre|piloter|d[ée]ployer|r[ée]duire|optimiser|organiser|d[ée]velopper|cr[ée]er)\b/i;
const languagePattern=/^(fran[çc]ais|anglais|allemand|italien|espagnol|portugais|n[ée]erlandais|russe|arabe|chinois|mandarin)(?:\s*[:\-–—/]\s*|\s+)(.*)$/i;
const languageLevel=/\b(langue maternelle|maternel(?:le)?|notions?|scolaire|professionnel(?:le)?(?: op[ée]rationnel(?:le)?)?|courant|bilingue|A[1-2]|B[1-2]|C[1-2]|TOEIC\s*\d+|IELTS\s*[\d.]+)\b/i;
const dateToken=String.raw`(?:\d{1,2}[./]\d{4}|\d{4}|(?:janvier|f[ée]vrier|mars|avril|mai|juin|juillet|ao[uû]t|septembre|octobre|novembre|d[ée]cembre)\s+\d{4})`;
const dateRange=new RegExp(`(?:depuis\\s+)?(${dateToken})\\s*(?:-|–|—|à|au)\\s*(${dateToken}|aujourd['’]hui|pr[ée]sent)|depuis\\s+(${dateToken})`,"i");
const metricPattern=/(?:[-+]?\d+(?:[.,]\d+)?\s*(?:%|€|CHF|k€|M€|collaborateurs?|personnes?|jours?|heures?|semaines?|mois|pi[èe]ces?|unit[ée]s?|projets?|sites?))/gi;
const knownSkills=/\b(5S|SMED|Kaizen|Lean|Six Sigma|DMAIC|AMDEC|FMEA|SAP|Excel|Power BI|AutoCAD|SolidWorks|Kanban|TPM|VSM)\b/gi;
const locationNames=/\b(Gen[èe]ve|Vaud|Lausanne|Neuch[aâ]tel|Jura|Fribourg|Valais|Zurich|B[âa]le|Berne|Moselle|Forbach|Lyon|Paris|France|Suisse)\b/i;
const slug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("fr").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const hash=(value:string)=>createHash("sha256").update(value).digest("hex").slice(0,20);
const sectionOf=(line:string)=>sectionPatterns.find(([,pattern])=>pattern.test(line.replace(/[:：]$/,"")))?.[0];
export function normalizeDocumentText(text:string):string[]{return text.normalize("NFC").replace(/[\u00a0\u202f]/g," ").replace(/[‐‑‒–—]/g,"–").replace(/^[ \t]*[•▪◦●·][ \t]*/gm,"• ").replace(/[ \t]+/g," ").split(/\r?\n/).map(line=>line.trim()).filter(Boolean);}
const findLastMatch=(values:readonly string[],predicate:(value:string)=>boolean)=>[...values].reverse().find(predicate);
const isSkillList=(value:string)=>value.split(/[,;]/).filter(Boolean).length>=3||[...value.matchAll(knownSkills)].length>=2;
const isDescriptive=(value:string)=>/^mon approche\b/i.test(value)||actionWords.test(value)||(/[.!?]$/.test(value)&&value.split(/\s+/).length>8);
const isRole=(value:string)=>roleWords.test(value)&&!isSkillList(value)&&!isDescriptive(value);
const forbiddenSkillFragment=/^(chiffr[ée]e? et document[ée]e?|en combinant|les co[uû]ts|puis [àa]|et |ainsi que )\b/i;
const isPlausibleSkill=(value:string)=>value.length>=2&&value.length<=100&&!forbiddenSkillFragment.test(value)&&!isDescriptive(value)&&(!/^[a-zà-öø-ÿ]/.test(value)||/\b(5S|SMED|Kaizen|Lean|Six Sigma|DMAIC|AMDEC|FMEA|SAP|Excel|Power BI|AutoCAD|SolidWorks|Kanban|TPM|VSM)\b/i.test(value));
const isLocation=(value:string)=>!isRole(value)&&!actionWords.test(value)&&(locationNames.test(value)||/^[\p{L}' -]{2,35},\s*[\p{L}' -]{2,35}$/u.test(value));
const isCompany=(value:string)=>!sectionOf(value)&&!isRole(value)&&!isLocation(value)&&!actionWords.test(value)&&value.length>=2&&value.length<=80&&(/\b(SA|SAS|SARL|GmbH|AG|France|Group|Industries?)\b/i.test(value)||/^[A-ZÀ-ÖØ-Ý0-9&.' -]+$/.test(value)||/^[A-ZÀ-ÖØ-Ý][\p{L}&.'-]+(?:\s+[A-ZÀ-ÖØ-Ý][\p{L}&.'-]+){1,4}$/u.test(value));
function linesOf(documentId:string,sections:readonly {label:string;text:string}[]):TextLine[]{void documentId;return sections.flatMap(section=>normalizeDocumentText(section.text).map((text,index)=>{const heading=sectionOf(text);return {text,section:section.label,line:index+1,...(heading?{heading}:{})};}));}
export function parseDocumentBlocks(documentId:string,sections:readonly {label:string;text:string}[]):ParsedBlock[]{const lines=linesOf(documentId,sections),blocks:ParsedBlock[]=[];let current:SectionKind="OTHER",lastExperience:ParsedBlock|undefined;for(let index=0;index<lines.length;index++){const item=lines[index]!;if(item.heading){current=item.heading;if(current!=="EXPERIENCE"&&current!=="ACHIEVEMENT")lastExperience=undefined;continue;}if(current==="LANGUAGE"){const match=item.text.match(languagePattern);if(match&&languageLevel.test(match[2]??"")){blocks.push({documentId,section:item.section,startLine:item.line,endLine:item.line,kind:"LANGUAGE",lines:[item.text],value:item.text,confidence:.92,resolved:true,anchor:item.text});continue;}current="OTHER";}
 const range=item.text.match(dateRange);if(range){const prefix=item.text.slice(0,range.index).trim().replace(/[|•,;\-–—]+$/g,"").trim(),rawWindow=lines.slice(Math.max(0,index-3),index).filter(line=>!line.heading).map(line=>line.text),window=rawWindow.flatMap(value=>value.split("|").map(part=>part.trim()).filter(Boolean));let role=isRole(prefix)?prefix:findLastMatch(window,isRole),location=isLocation(prefix)?prefix:findLastMatch(window,isLocation),company=findLastMatch(window,value=>isCompany(value)&&value!==role&&value!==location);if(role&&company===role)company=undefined;if(location&&isRole(location))location=undefined;const startDate=(range[1]??range[3])?.trim(),endDate=range[2]?.trim()??(range[3]?"présent":undefined),resolved=Boolean(company&&role),anchor=[...rawWindow,item.text].join("\n"),block:ParsedBlock={documentId,section:item.section,startLine:Math.max(1,item.line-rawWindow.length),endLine:item.line,kind:"EXPERIENCE",lines:[...rawWindow,item.text],...(company?{company}:{}),...(role?{role}:{}),...(location?{location}:{}),...(startDate?{startDate}:{}),...(endDate?{endDate}:{}),confidence:resolved ? .92 : .55,resolved,anchor};blocks.push(block);lastExperience=block;current="EXPERIENCE";continue;}
 if(item.text.startsWith("• ")&&(current==="EXPERIENCE"||current==="ACHIEVEMENT")&&lastExperience){blocks.push({documentId,section:item.section,startLine:item.line,endLine:item.line,kind:"ACHIEVEMENT",lines:[item.text],value:item.text.slice(2).trim(),confidence:.86,resolved:lastExperience.resolved,anchor:lastExperience.anchor});continue;}
 if(current==="SKILL"){const value=item.text.replace(/^•\s*/,"");if(isPlausibleSkill(value))blocks.push({documentId,section:item.section,startLine:item.line,endLine:item.line,kind:"SKILL",lines:[item.text],value,confidence:.78,resolved:true,anchor:item.text});continue;}if(current==="EDUCATION"){blocks.push({documentId,section:item.section,startLine:item.line,endLine:item.line,kind:"EDUCATION",lines:[item.text],value:item.text.replace(/^•\s*/,""),confidence:.78,resolved:true,anchor:item.text});continue;}
 }return blocks;}
function fact(category:FactCategory,entityId:string,field:string,value:string,source:SourceRef,confidence:number,status:FactStatus):CandidateFact{const id=`fact:${hash(`${category}|${entityId}|${field}|${value.toLocaleLowerCase("fr")}`)}`;return {id,type:`${category}.${field}`.toUpperCase(),category,entityId,field,key:`${entityId}:${field}`,canonical:value,structuredValue:value,source,sources:[source],confidence,status,allowedAlternatives:[],tags:[],active:true,origin:"AUTOMATIC",history:[{at:new Date().toISOString(),action:"CREATED",actor:"extractor"}]};}
export function proposeFacts(documentId:string,name:string,sections:readonly {label:string;text:string}[]):CandidateFact[]{const output:CandidateFact[]=[];for(const block of parseDocumentBlocks(documentId,sections)){const source={documentId,name,location:`${block.section}, lignes ${block.startLine}-${block.endLine}`};if(block.kind==="EXPERIENCE"){const entityId=block.resolved?`experience:${slug(`${block.company}-${block.role}`)}`:`experience:unresolved:${slug(documentId)}:${hash(`${block.section}|${block.anchor}`)}`,status:FactStatus=block.resolved?"PROPOSED":"NEEDS_CONFIRMATION";for(const [field,value] of [["company",block.company],["role",block.role],["location",block.location],["startDate",block.startDate],["endDate",block.endDate]] as const)if(value)output.push(fact("EXPERIENCE",entityId,field,value,source,block.confidence,status));continue;}if(block.kind==="ACHIEVEMENT"&&block.value){const experience=output.filter(value=>value.category==="EXPERIENCE").at(-1),experienceId=experience?.entityId,entityId=`achievement:${hash(`${documentId}|${block.section}|${block.anchor}|${block.value}`)}`,status:FactStatus=block.resolved&&experienceId?"PROPOSED":"NEEDS_CONFIRMATION";output.push(fact("ACHIEVEMENT",entityId,"action",block.value,source,block.confidence,status));if(experienceId)output.push(fact("ACHIEVEMENT",entityId,"experienceId",experienceId,source,.9,status));for(const metric of [...block.value.matchAll(metricPattern)].map(match=>match[0].trim()))output.push(fact("ACHIEVEMENT",entityId,"metric",metric,source,.9,status));for(const skill of [...new Set([...block.value.matchAll(knownSkills)].map(match=>match[1]!))])output.push(fact("SKILL",`skill:${slug(skill)}`,"competency",skill,source,.88,"PROPOSED"));continue;}if(block.value&&(block.kind==="SKILL"||block.kind==="EDUCATION"||block.kind==="LANGUAGE")){const category:FactCategory=block.kind,field=block.kind==="SKILL"?"competency":block.kind==="EDUCATION"?"qualification":"level";for(const value of block.kind==="SKILL"?block.value.split(/[,;•]/).map(item=>item.trim()).filter(Boolean):[block.value])output.push(fact(category,`${block.kind.toLowerCase()}:${slug(value)}`,field,value,source,block.confidence,"PROPOSED"));}}
 return consolidateFacts(output);}
